logging:
  level:
    io.camunda.zeebe.client.impl.ZeebeCallCredentials: ERROR

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:29092

zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
       plaintext: true
  kafka-exporter:
    topic-name: zeebe

common:
  enabled: true
  keycloak:
    url: http://localhost:18080
    realm: camunda-platform
  client-id: zeebe
  client-secret: zecret

vanillabp:
  workflow-modules:
    demo:
      adapters:
        camunda8:
          resources-location: classpath*:/processes8