logging:
  level:
    io.camunda.zeebe.client.impl.ZeebeCallCredentials: ERROR

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:29092

camunda:
  client:
    mode: oidc
    auth:
      oidc-type: keycloak
      issuer: http://localhost:18080/auth/realms/camunda-platform
      client-id: zeebe
      client-secret: zecret
    zeebe:
      enabled: true
      base-url: http://localhost:26500
      defaults:
        enabled: false
    operate:
      enabled: false
    tasklist:
      enabled: false
    optimize:
      enabled: false
    identity:
      enabled: false

vanillabp:
  workflow-modules:
    demo:
      adapters:
        camunda8:
          resources-location: classpath*:/processes8