logging:
  level:
    io.camunda.zeebe.client.impl.ZeebeCallCredentials: ERROR

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:29092

camunda:
  client:
    mode: oidc
    auth:
      oidc-type: keycloak
      issuer: http://localhost:18080/auth/realms/camunda-platform
      client-id: zeebe
      client-secret: zecret
    zeebe:
      enabled: true
      base-url: http://localhost:26500
      prefer-rest-over-grpc: false
      audience: zeebe-api
    operate:
      enabled: true
      base-url: http://localhost:8081
      audience: operate-api
    tasklist:
      enabled: true
      base-url: http://localhost:8082
      audience: tasklist-api
    optimize:
      enabled: true
      base-url: http://localhost:8083
      audience: optimize-api
    identity:
      enabled: true
      base-url: http://localhost:8084
      audience: identity-api
  zeebe:
    kafka-exporter:
      topic-name: zeebe

vanillabp:
  workflow-modules:
    demo:
      adapters:
        camunda8:
          resources-location: classpath*:/processes8