logging:
  level:
    io.vanillabp: DEBUG

server:
  port: 8078

spring:
  application:
    name: Demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./demodb.h2;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

workerId: test

vanillabp:
  cockpit:
    template-loader-path: "localhost"
  workflows:
    - workflow-module-id: "demo"
      workflow-module-uri: "http://localhost:8078/demo"
      task-provider-api-path: "/task-provider/v1"
      ui-uri-path: "/remoteEntry.js"
      ui-uri-type: "WEBPACK_MF_REACT"
      bpmn-description-language: "de"
      bpmn-process-id: "DemoWorkflow"
    - workflow-module-id: "demo"
      workflow-module-uri: "http://localhost:8078/demo"
      task-provider-api-path: "/task-provider/v1"
      ui-uri-path: "/remoteEntry.js"
      ui-uri-type: "WEBPACK_MF_REACT"
      bpmn-description-language: "de"