vanillabp:
  cockpit:
    kafka:
      workflow-topic: "workflows"
      user-task-topic: "user-tasks"
      workflow-module-topic: "modules"

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092