logging:
  level:
    io.vanillabp: DEBUG

server:
  port: 8078

spring:
  application:
    name: Demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./demodb.h2;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:db/changelog/demo-aggregate.yaml
    enabled: true

workerId: test

vanillabp:
  cockpit:
    template-loader-path: "classpath:template"
  workflow-modules:
    demo:
      cockpit:
        workflow-module-uri: "http://localhost:8078"
        task-provider-api-path: "/task-provider/v1"
        workflow-provider-api-path: "/workflow-provider/v1"
        ui-uri-path: "/remoteEntry.js"
        ui-uri-type: "WEBPACK_MF_REACT"
        bpmn-description-language: "de"
        i18n-languages: ["de"]
